config/routes.rb
Rails.application.routes.draw do
  resources :user_coins, only: [:create, :destroy]
  devise_for :users
  root :to => 'welcome#index'
  get 'welcome/index'
  get 'my_portfolio', to: 'users#my_portfolio'
  get 'search_coin', to: 'coins#search'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/coin.rb
class Coin < ApplicationRecord

  has_many :user_coins
  has_many :users, through: :user_coins

  validates :name, :ticker, presence: true

  @@base_uri = 'https://api.coincap.io/v2/assets/'

  def self.new_lookup(name)
    coin_name = name.downcase
    res = get_coin_info(coin_name)

    begin
      new(ticker: res["symbol"], name: coin_name, last_price: res["priceUsd"].to_f.round(2))
    rescue => exception
      return nil
    end
  end

  def self.check_db(name)
    where(name: name).first
  end

  def self.update_price(name)
    coin = where(name: name).first
    res = get_coin_info(name)

    coin.last_price = res["priceUsd"].to_f.round(2)

    coin.save
  end

  def self.get_coin_info(name)
    uri = URI(@@base_uri + name)
    JSON.parse(Net::HTTP.get(uri))["data"]
  end
end

app/models/sentiment.rb
class Sentiment < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord

  has_many :user_coins
  has_many :coins, through: :user_coins
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def coin_already_tracked?(name)
    coin = Coin.check_db(name)
    return false unless coin
    coins.where(id: coin.id).exists?
  end

  def under_coin_limit?
    coins.count < 10
  end

  def can_track_coin?(name)
    under_coin_limit? && !coin_already_tracked?(name)
  end
  
  def full_name
    return "#{first_name} #{last_name}" if first_name || last_name
    "Anonymous"
  end
end

app/models/user_coin.rb
class UserCoin < ApplicationRecord
  belongs_to :user
  belongs_to :coin
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/coins_controller.rb
class CoinsController < ApplicationController
  
  def search

    if params[:coin].present?
      @coin = Coin.new_lookup(params[:coin])
      if @coin
        respond_to do |format|
          format.js { render partial: 'users/results' }
        end
      else
        respond_to do |format|
          flash.now[:alert] = "Please enter a valid coin name to search"
          format.js { render partial: 'users/results' }
        end
      end
    else
      respond_to do |format|
        flash.now[:alert] = "Please enter a coin name to search"
        format.js { render partial: 'users/results' }
      end
    end
  end
end

app/controllers/user_coins_controller.rb
class UserCoinsController < ApplicationController

  def create
    coin = Coin.check_db(params[:name])
    
    if coin.blank?
      coin = Coin.new_lookup(params[:name])
    end

    coin.save

    @user_coin = UserCoin.create(user: current_user, coin: coin)
    flash[:notice] = "Coin #{coin.name} was successfully added to your portfolio"
    redirect_to my_portfolio_path
  end

  def destroy
    coin = Coin.find(params[:id])
    user_coin = UserCoin.where(user_id: current_user.id, coin_id: coin.id).first
    user_coin.destroy
    flash[:notice] = "#{coin.name} was successfully removed from portfolio"
    redirect_to my_portfolio_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def my_portfolio
    current_user.coins.each do |coin|
      Coin.update_price(coin.name)
    end
    @tracked_coins = current_user.coins
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @coins_count = current_user.coins.count
    @sentiment_score = sentiment_score
  end

  def sentiment_score
    sentiment = Sentiment.first
    sentiment.score
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_coins_helper.rb
module UserCoinsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/coins/_list.html.erb
<%= render  "users/results" %>
  <div class="row">
    <div class="col-9">
      <table class="table table-bordered table-hover">
        <thead>
          <tr>
            <th scope="col">Ticker</th>
            <th scope="col">Name</th>
            <th scope="col">Price</th>
            <th scope="col">Actions</th>
          </tr>
        </thead>
        <tbody>
          <% @tracked_coins.each do |coin| %>
            <tr>
              <th scope="row"><%= coin.ticker %></th>
              <td><%= coin.name %></td>
              <td><%= coin.last_price %></td>
              <td><%= link_to  "Remove", user_coin_path(coin), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-sm btn-warning" %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>

app/views/layouts/_messages.html.erb
<% if notice %>
	<div class='alert alert-success'>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
		<%= notice %>
	</div>
<% end %>

<% if alert %>
	<div class='alert alert-danger'>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
		<%= alert %>
	</div>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
    <%= link_to  "CryptoAdvice", root_path, class: "navbar-brand" %>
        <% if current_user %>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item <%= 'active' if request.path ==  my_portfolio_path %>">
                        <%= link_to 'My Portfolio', my_portfolio_path, class: "nav-link" %>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Profile
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <%= link_to edit_user_registration_path, class: "dropdown-item" do %>
                                <%= fa_icon 'edit' %> Edit Profile
                            <% end %>
                        </div>
                    </li>
                </ul>
                <ul class ="navbar-nav ml-auto">
                    <li class="nav-item user-name">
                        <%= fa_icon 'user'%> <%= current_user.full_name %>
                    </li>
                    <li class="nav-item">
                        <%= link_to  'Sign out', destroy_user_session_path, class: "btn btn-xs btn-danger logout-button", method: :delete %>
                    </li>
                </ul>
            </div>
        <% end %>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CryptoAdviceRails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <div class="container">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/users/_results.html.erb
<div class="results-block">
    <%= render 'layouts/messages' %>
</div>

<% if @coin %>
  <div class="card card-header results-block">
    <strong>Symbol: </strong> <%= @coin.ticker %>
    <strong>Name: </strong> <%= @coin.name %>
    <strong>Price: </strong> <%= @coin.last_price %>
    <% if current_user.can_track_coin?(@coin.name) %>
      <%= link_to  "Add to portfolio", user_coins_path(user: current_user, name: @coin.name), class: "btn btn-xs btn-success", method: :post %>
    <% else %>
      <span class="badge badge-secondary">
        You are already tracking
        <% if !current_user.under_coin_limit? %>
          10 coins
        <% end %>
        <% if current_user.coin_already_tracked?(@coin.name) %>
          this coin
        <% end %>
      </span>
    <% end %>
  </div>
<% end %>

app/views/users/_results.js.erb
document.querySelector('#results').innerHTML = '<%= escape_javascript(render 'users/results.html') %>'

app/views/users/my_portfolio.html.erb
<h1>My Portfolio</h1>

<div class="search-area">
  <h3>Search Coins</h3>
  <%= form_tag search_coin_path, remote: true, method: :get do %>
    <div class="form-group row">
      <div class="col-sm-9 no-right-padding">
        <%= text_field_tag :coin, params[:coin], placeholder: "Coin Name", autofocus: true, class: "form-control form-control-lg" %>
      </div>
      <div class="col-sm-3 no-left-padding">
        <%= button_tag type: :submit, class: "btn btn-success" do %>
          <%= fa_icon 'search 2x' %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>
<div id="results">
</div>
<% if !@tracked_coins.empty? %>
  <%= render 'coins/list' %>
<% end %>

app/views/welcome/index.html.erb
<h1>Welcome to Crypto Advice Ultimate</h1>

<div class="col-9 search-area d-flex justify-content-center">
  <h3>You are tracking <%= @coins_count %> coins in your portfolio</h3>
</div>
<div class="col-9 search-area d-flex justify-content-center">
  <h1>Crypto Sentiment score: <%= @sentiment_score %>% </h1>
</div>
<div class="col-9 search-area d-flex justify-content-center">
  <%= link_to 'My Portfolio', my_portfolio_path, class: "btn btn-primary" %>
</div>